export const ZOOM_CITY = 13
export const ZOOM_MUNICIPALITY = 10
export const zoomHalfNorway = 6
export const ZOOM_NORWAY = 4.3
export const ZOOM_REGION = 8
export const MIN_ZOOM_DEFAULT = 3.7
export const PROJECTION = 'EPSG:3857'
export const NORGES_GRUNNKART = 'norges_grunnkart'
export const EUROPA_FORENKLET = 'europa_forenklet'
export const DEFAULT_MARKER_SCALE = 0.5
export const DEFAULT_MARKER_OPACITY = 1
export const DEFAULT_START_COORDINATES = { lat: 65, long: 10 }
export const DEFAULT_ANIMATION_SPEED = 1000
export const DEFAULT_CLUSTER_DISTANCE = 20
export const DEFAULT_CLUSTER_MIN_DISTANCE = 10
