export const ZOOM_CITY = 13
export const ZOOM_MUNICIPALITY = 10
export const ZOOM_HALF_NORWAY = 6
export const ZOOM_NORWAY = 4
export const ZOOM_REGION = 8
export const MIN_ZOOM_DEFAULT = 3.7
export const PROJECTION = 'EPSG:3857'
export const NORGES_GRUNNKART = 'norges_grunnkart'
export const EUROPA_FORENKLET = 'europa_forenklet'
export const DEFAULT_MARKER_SCALE = 0.7
export const DEFAULT_MARKER_OPACITY = 1
export const DEFAULT_START_COORDINATES = { lat: 65, long: 17 }
export const DEFAULT_ANIMATION_SPEED = 1000
export const DEFAULT_CLUSTER_DISTANCE = 30
export const DEFAULT_CLUSTER_MIN_DISTANCE = 20
export const DEFAULT_CLUSTER_RADIUS = 8
export const DEFAULT_CLUSTER_DISPLACEMENT = [15, 15]
export const DEFAULT_CLUSTER_SIZE_SCALE = 1.3
export const DEFAULT_CLUSTER_OFFSET_X = 15
export const DEFAULT_CLUSTER_OFFSET_Y = -15
export const DEFAULT_CLUSTER_FIT_PADDING = 200
export const DEFAULT_OVERLAY_OFFSET = [25, 0]
export const CLICK_POPUP_OVERLAY = 'ClickPopupOverlay'
export const HOVER_POPUP_OVERLAY = 'HoverPopupOverlay'
