name: Bump designsystem versions in mattilsynet-web

on:
  workflow_dispatch:
  workflow_call:

jobs:
  open-pr:
    runs-on: ubuntu-latest
    name: 'Bump DS version and open PR'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 'Get latest commit message'
        id: git_log
        run: echo "latest_commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: 'Set git user'
        run: |
          git config --global user.name "Designsystem"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - uses: actions/checkout@v4
        with:
          repository: Mattilsynet/mattilsynet-web
          ssh-key: ${{ secrets.MATTILSYNET_WEB_DEPLOY_KEY }}
          ref: main
          path: mattilsynet-web

      - name: 'Bump versions'
        working-directory: mattilsynet-web/frontend-app
        run: |
          npx npm-check-updates '/^@mattilsynet.*$/' -u
          npm i
          git checkout -b bump-designsystem-${{ github.run_id }}
          git add .
          git commit -m "chore: bump designsystem packages"
          git push origin bump-designsystem-${{ github.run_id }}

      - name: 'Open PR'
        working-directory: mattilsynet-web/frontend-app
        env:
          GH_TOKEN: ${{ secrets.MATTILSYNET_WEB_PAT }}
        run: |
          gh pr create --title "chore: bump DS - ${{ steps.git_log.outputs.latest_commit_message }}" --body "automatic ds bump" --head "bump-designsystem-${{ github.run_id }}" --base main --label dependencies
