name: publish node package
run-name: Build XP app "${{ github.ref_name }}" by @${{ github.actor }}

#undo!
on:
  workflow_dispatch:

jobs:
  publish:
    name: 'Publish package'
    secrets: inherit
    uses: Mattilsynet/designsystem/.github/workflows/publish.yml@MTP-1305-automatisering-publish-job-for-designsystem
    with:
      working-directory: 'mt-kit/core/svelte'
