name: Publish svelte package
run-name: Publishing new svelte package @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: Semantic bump
        type: choice
        options:
          - patch
          - minor
          - major
        default: patch

jobs:
  publish:
    name: 'Publish package'
    if: github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    secrets: inherit
    uses: Mattilsynet/designsystem/.github/workflows/publish.yml@main
    with:
      working-directory: 'mt-kit/core/svelte'
      version-type: ${{ inputs.version-type }}
