name: Publish package
run-name: Publish package by @${{ github.actor }}

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: true
      version-type:
        type: string
        default: patch

jobs:
  publish:
    name: 'Bump version and Publish package'
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login != 'dependabot[bot]' && github.event.pull_request.merged
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Get project name
        id: split
        env:
          DIR: ${{ inputs.working-directory }}
        run: echo "project_name=${DIR##*/}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3

      - name: 'Bump version'
        uses: phips28/gh-action-bump-version@v10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: ${{ inputs.working-directory }}
        with:
          tag-prefix:  'v'
          tag-suffix: -${{ steps.split.outputs.project_name }}
          target-branch: 'main'
          major-wording: '#major'
          minor-wording: '#minor'
          patch-wording: '#patch'
          check-last-commit-only: 'true'
          bump-policy: 'ignore'
          version-type: ${{ inputs.version-type }}

      - name: 'Setup node'
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@mattilsynet'
          cache: 'npm'
          cache-dependency-path: |
            mt-kit/core/svelte/package-lock.json
            mt-kit/core/react/package-lock.json
            mt-kit/core/css/package-lock.json

      - name: 'Publish to GitHub registry'
        run: |
          git pull
          git config --global user.email "${{ github.actor }}@users.noreply.github.com" && git config --global user.name "${{ github.actor }}"
          npm install
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
