name: Publish react package
run-name: Publishing new react package @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: Semantic bump
        type: choice
        options:
          - patch
          - minor
          - major
        default: patch
  pull_request:
    branches:
      - main
    types:
      [closed]
    paths:
      - mt-kit/core/react/**

jobs:
  publish:
    name: 'Publish package'
    secrets: inherit
    uses: Mattilsynet/designsystem/.github/workflows/publish.yml@main
    with:
      working-directory: 'mt-kit/core/react'
      version-type: ${{ inputs.version-type }}
