name: Publish all changed packages
run-name: Publishing new package(s) @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: Semantic bump
        type: choice
        options:
          - patch
          - minor
          - major
        default: patch
  pull_request:
    branches:
      - main
    types:
      [closed]
    paths:
      - mt-kit/core/**

jobs:
  changes:
    if: github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: 'Get changed directories'
    outputs:
      css: ${{ steps.changed-files.outputs.css_any_changed }}
      svelte: ${{ steps.changed-files.outputs.svelte_any_changed }}
      react: ${{ steps.changed-files.outputs.react_any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: 'Get all css, svelte and react files that have changed'
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          since_last_remote_commit: true
          files_yaml: |
            css:
              - mt-kit/core/css/**
            svelte:
              - mt-kit/core/svelte/**
            react:
              - mt-kit/core/react/**

      - name: 'Changed files output'
        run: echo "${{ toJSON(steps.changed-files.outputs) }}"

  publish-css:
    name: 'Publish css package'
    if: ${{ needs.changes.outputs.css == 'true' }}
    needs: [changes]
    secrets: inherit
    uses: Mattilsynet/designsystem/.github/workflows/publish.yml@main
    with:
      working-directory: 'mt-kit/core/css'
      version-type: ${{ inputs.version-type }}

  publish-svelte:
    name: 'Publish svelte package'
    if: always() && ${{ needs.changes.outputs.svelte == 'true' }}
    needs: [changes, publish-css]
    secrets: inherit
    uses: Mattilsynet/designsystem/.github/workflows/publish.yml@main
    with:
      working-directory: 'mt-kit/core/svelte'
      version-type: ${{ inputs.version-type }}

  publish-react:
    name: 'Publish react package'
    if: false && always() && ${{ needs.changes.outputs.react == 'true' }}
    needs: [changes, publish-svelte]
    secrets: inherit
    uses: Mattilsynet/designsystem/.github/workflows/publish.yml@main
    with:
      working-directory: 'mt-kit/core/react'
      version-type: ${{ inputs.version-type }}

  bump-mattilsynet-web:
    name: 'Bump designsystem versions in mattilsynet-web'
    if: |
      always() &&
      needs.publish-css.result == 'success' ||
      needs.publish-svelte.result == 'success' ||
      needs.publish-react.result == 'success'
    needs: [ publish-css, publish-svelte, publish-react ]
    secrets: inherit
    uses: Mattilsynet/designsystem/.github/workflows/bump.mattilsynet-web.yml@main
